services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.3-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./htpasswd:/etc/nginx/htpasswd

      # adding extra configs to the main nginx config
      - ./conf.d/gzip.conf:/etc/nginx/conf.d/gzip.conf:ro
      - ./conf.d/upload-size.conf:/etc/nginx/conf.d/upload-size.conf:ro
      - ./conf.d/proxy-cache.conf:/etc/nginx/conf.d/proxy-cache.conf:ro

      # Add nginx cache volume
      - nginx-cache:/var/cache/nginx/proxy_cache

      - static:/usr/share/nginx/static/
      - media:/usr/share/nginx/media/
    logging:
      driver: "json-file"
      options:
        max-size: 30m
        max-file: 10

    networks:
      - nginx-proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    environment:
      - DEFAULT_EMAIL=serhii.riabcheniuk@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    networks:
      - nginx-proxy


      #  nginx:
#    image: nginx:alpine
#    labels:
#      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
#    container_name: nginx
#    restart: unless-stopped
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#      - ./vhost.d:/etc/nginx/vhost.d
#      - ./html:/usr/share/nginx/html
#      - ./certs:/etc/nginx/certs:ro

#  nginx-gen:
#    image: jwilder/docker-gen
#    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
#    container_name: nginx-gen
#    restart: unless-stopped
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#      - ./vhost.d:/etc/nginx/vhost.d
#      - ./html:/usr/share/nginx/html
#      - ./certs:/etc/nginx/certs:ro
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
#
#  nginx-letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: nginx-letsencrypt
#    restart: unless-stopped
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#      - ./vhost.d:/etc/nginx/vhost.d
#      - ./html:/usr/share/nginx/html
#      - ./certs:/etc/nginx/certs:rw
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
#      NGINX_PROXY_CONTAINER: "nginx"

volumes:
  static:
    name: "nginx_proxy_static"
  media:
    name: "nginx_proxy_media"
  nginx-cache:
    name: "nginx_proxy_cache"

networks:
  nginx-proxy:
    name: nginx-proxy